// Argument names and defaults follow agent_cowork_memory/mcp_server.py.
export const TOOL_DOCS = [
  {
    name: "chats",
    description: "Lists recent chats from every agent in the project, and marks the ones ACM started.",
    call: 'chats(repo_path="/path/to/acme-api", limit=20)',
    result: 'codex   12m  "rate limit login"   delegated\ncursor   2h  "fix cart reducer"\nclaude   1d  "plan the v2 api"',
    params: [
      ["repo_path", "Required. The project's working directory."],
      ["limit", "Optional. Maximum chats to return; defaults to 20."],
    ],
    detail: "Returns the agent, chat ID, last update, folder, shared task, first user message and delegated job ID. Use the chat ID the user chooses with resume. Chats can come from the project, a folder inside it, or a parent folder.",
  },
  {
    name: "resume",
    description: "Asks which chat to continue when there are several, then reads it and picks up the task.",
    call: 'resume(repo_path="/path/to/acme-api", source="codex")',
    result: "2 chats from codex. Which one?\n  1  rate limit login · 12m\n  2  flaky checkout · 3h",
    params: [
      ["repo_path", "Required. The project's working directory."],
      ["source", "Optional. Filter by agent; omit to consider the other agents."],
      ["chat", "Optional. The chat ID selected by the user."],
      ["limit", "Optional. Recent messages to read; defaults to 30."],
    ],
    detail: "If the response contains choose, present the choices and wait for the user's selection, then call resume again with that chat ID. Never choose for them. A resolved chat returns its recent messages and attaches you to its shared task so work can continue without pasted context.",
  },
  {
    name: "attach",
    description: "Starts or joins a shared task.",
    call: 'attach(repo_path="/path/to/acme-api", label="login limiter", title="Rate-limit login")',
    result: 'session: acm_s_…\ntask: acm_t_…\nstatus: open',
    params: [
      ["repo_path", "Required. Your working directory."],
      ["label", "Required. A readable label for this agent session."],
      ["title", "Required when creating a task. Omit when joining one."],
      ["task", "Required when joining a task. An existing task ID; omit when creating one."],
      ["goal", "Optional. The task's objective."],
      ["native_id", "Optional. The agent's own chat or session ID."],
    ],
    detail: "Call this first for shared task work. Pass exactly one of title (create) or task (join). Keep the returned session ID: context, note_add, note_search and delegate_wait use it. The server identifies your agent from its MCP client or --harness setting; label does not choose the agent.",
  },
  {
    name: "context",
    description: "Reads the task, notes, who is working and which files are held. Pass hold to claim files.",
    call: 'context(session="acm_s_…", hold=["src/routes/login.ts"])',
    result: "held  src/routes/login.ts\ncursor holds tests/login.rateLimit.test.ts",
    params: [
      ["session", "Required. The session ID returned by ACM."],
      ["hold", "Optional. Repo-relative file paths to claim; [] releases your claims."],
    ],
    detail: "Call before working and again before editing. Read the task, project notes, active sessions and current claims. Leave paths in busy alone. Send the full set of paths you need to hold; omit hold for a read without changing your claims. Release your files with hold=[] when finished.",
  },
  {
    name: "note_add",
    description: "Saves a short-term or long-term note.",
    call: 'note_add(session="acm_s_…", text="Chose Postgres over SQLite", tier="long")',
    result: "saved · long-term · visible to every agent",
    params: [
      ["session", "Required. Your ACM session ID."],
      ["text", "Required. The note to share with the project."],
      ["tier", 'Optional. "short" (default) for progress; "long" for durable decisions.'],
      ["kind", "Optional. A category for the note."],
      ["days", "Optional. Short-note lifetime; defaults to 7 days."],
      ["supersedes", "Optional. The ID of an outdated note this replaces."],
      ["source", "Optional. Where the information came from."],
    ],
    detail: "Use long notes for decisions, preferences and conventions that should stay available. Short notes expire. Replace an outdated note using supersedes so agents see the current decision. ACM already records delegated job results; do not duplicate them as notes.",
  },
  {
    name: "note_search",
    description: "Finds notes from the project.",
    call: 'note_search(session="acm_s_…", query="database")',
    result: '1 note\n  "Chose Postgres over SQLite"  claude · 3d',
    params: [
      ["session", "Required. Your ACM session ID."],
      ["query", "Required. Text to search for in project notes."],
      ["task", "Optional. Limit results to a shared task ID."],
    ],
    detail: "Search before asking someone to repeat a decision. Expired, forgotten and superseded notes are excluded, so results reflect the project's current memory. Omit task to search across the project.",
  },
  {
    name: "delegate",
    description: "Starts other agents with a brief, in Herdr panes or in the background, and waits.",
    call: 'delegate(\n  repo_path="/path/to/acme-api",\n  session="acm_s_…",\n  summary="Add rate limiting to login",\n  tasks=[{\n    "to": "codex",\n    "task": "Add the login limiter",\n    "done_when": "Login returns 429 after 5 attempts",\n    "context": "Edit src/middleware/rateLimit.ts"\n  }]\n)',
    result: "codex   started in Herdr pane\ncursor  busy · one agent per kind per folder",
    params: [
      ["repo_path", "Required. The project's working directory."],
      ["summary", "Required. The problem, understandable without this chat."],
      ["tasks", "Required. A list of briefs. Each needs to and task; done_when and context are optional."],
      ["session", "Optional. Your existing session ID; otherwise keep the returned one."],
    ],
    detail: "Delegate when the user asks for another agent. Current targets are codex, claude, cursor and opencode. There is one agent per kind per folder; busy means an existing agent already occupies that slot. Agents receive the brief and claim files through context. A delegated worker cannot delegate again: ACM returns not_allowed. If the response includes next, keep calling delegate_wait until no job is running.",
  },
  {
    name: "delegate_wait",
    description: "Keeps waiting on this chat's delegated agents.",
    call: 'delegate_wait(session="acm_s_…")',
    result: "codex   done\ncursor  needs_approval · run npm run db:migrate",
    params: [["session", "Required. The session ID for the delegation."]],
    detail: "Waits up to 45 seconds more and reports each job's state. Call again while jobs are running, then report their results. For needs_approval, bring the requested action back to the user; approval is handled through the delegating chat. For blocked, tell the user what needs an answer in the agent's Herdr pane. Do not answer on their behalf.",
  },
];
